name: n8n-with-postgres
services:
  postgres:
    container_name: n8n_db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: n8n_engine
    image: docker.n8n.io/n8nio/n8n
    restart: always
    hostname: n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL
    ports:
      - 5678:5678
    links:
      - postgres
      - tailscale-nginx
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  tailscale-nginx:
    container_name: n8n_tailscale
    image: tailscale/tailscale:latest
    hostname: n8n_tailscale
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    command: > 
      sh -c "
      tailscaled &
      sleep 5 &&
      tailscale up ${TS_EXTRA_ARGS} && tailscale serve clear svc:n8n &&
      tailscale serve --service=svc:n8n http://localhost:80 &&
      wait
      "
  nginx:
    container_name: n8n_nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - n8n
    network_mode: service:tailscale-nginx

volumes:
  db_storage:
  n8n_storage:
